### ISSUE TITLE
Arbitrarily oritented 1D structural model not solving

### ISSUE THREAD

**Issue by JohnDN90** [MASTmultiphysics/mast-multiphysics#40]
The issue is that 1D structural elements do not seem to be constructed properly when they not aligned with the x-axis.  For example, the 1D bar extension example works fine when it is oriented along the x-axis with force acting in x-direction, but if I try to solve the same problem with the bar oriented along the y-axis instead with force acting in y-direction, it no longer solves.

I've attached a simple source file that demonstrates this.

I came about this issue when trying to solve the 10 bar truss problem, imported into MAST from an input file.  In that case, I narrowed it down to the weighted Jacobian, from get_JxW(), is becoming NaN in some cases which results in NaNs in the residual and the program terminates, with a zero solution and no error code.  I tried input files for the 3 bar truss and a vertically oriented 1 bar extension case, and saw the same behavior.  

I tried an unmodified (i.e. from GitHub) version of MAST with the example file (attached) to rule out an issue with my input file reader or my modified MAST code. I didn't examine the weighted Jacobian for the example attached (I didn't modify the MAST source to print out this value), but I suspect the same issue is occurring here.

Although untested, I feel like this issue could spill over into other structural models with 2D and 3D elements, that utilize 1D elements as well.
[bar_extension_vertical_pointload.zip](https://github.com/MASTmultiphysics/mast-multiphysics/files/3714991/bar_extension_vertical_pointload.zip)

Edit 1: Fixed typo

**Comment by JohnDN90** [comment]
After further testing, it looks like this has to do with the orientation of the 1D element.  For an element along the x-axis, the orientation of [0,1,0], works but fails when the element is along the y-axis. For the y-axis, [0,1,0] causes the failure originally described, but works if the orientation is changed to [1,0,0].

**Comment by manavbhatia** [comment]
The orientation of local y axis combined with the local x-axis of the element is needed to uniquely define the plane that the element lies in. So, an element along the y-axis and orientation vector also along the y-axis does not have a linearly independent basis. 

Am I understanding that this works with the correct orientation vector?

**Comment by manavbhatia** [comment]
Note that the orientation vector needs to be any vector, not parallel to the element, in the plane of the element. So, if your element is along (0, 1, 0) these are valid examples of orientation vectors (1, 1, 0), (1, 0, 0), (0, 0, 1), (1, 1, 1), etc. Anything that is not a scalar multiple of (0, 1, 0) will be fine.

If the three truss bars are in the x-y plane then you can define any vector in this plane, that is not parallel to either element, as the y-orientation vector for all three elements. This way you will need only one section property card.  

Another way is to define the orientation-vector to be along the z-axis (0, 0, 1). This way you will need only one section card and you don't have to worry about finding a linearly independent basis for this vector since all your element are in the x-y plane.

**Comment by JohnDN90** [comment]
Hmm, alright.  I was thinking along those same lines.  When importing the a model from another FEA program (i.e. Nastran) the beam orientations should be defined already in the input, so that isn't really an issue there (other than making sure MAST and the input define the orientation the same way and make adjustments if not).  The issue I'm particularly dealing with is that Nastran doesn't define an orientation for CROD elements, since its not needed.  However, MAST still expects the orientation to be there and has problems if its not.

I was trying to come up with a simple way of defining an orientation vector that is linearly independent of all all other vectors defined by CROD elements in the model.  For a large arbitrary 3D model with many CROD elements, this may not be practical though.  Perhaps a better way may be to modify the MAST source code to check if bending is required, and if not then don't require the orientation vector.  Any thoughts on what might be the best way to approach this?

**Comment by manavbhatia** [comment]
There are other similar issues in the data structure where something is required even when it is not really needed. For example, the section offset is required for both beams and plates even if it can be assumed to be zero when not present. These could be streamlined with some effort, if they are a huge hassle. 

An arbitrarily oriented 1D element needs a map from the global to the local coordinate system so that the stiffness matrix can be transformed from the local to the global system before being added to the global stiffness matrix. Likewise for element vectors. How would a pure extension element (like a CROD) map to the global coordinate system uniquely without knowing one additional vector to define a plane? 

Also, please note that the hy, hz thickness values are with reference to the local y- and z-axes, respectively. So, if you have an element along (1, 0, 0) with oriented vector as (0, 1, 0) then hy, hz will serve as the thickness in the global y- and z- axes (since the local and global y- and z- are parallel). However, if you define (0, 0, 1) as the orientation vector then the hy, hz will serve as thickness along the global z- and y- axes, respectively.

**Comment by manavbhatia** [comment]
I am suspecting that a CROD element requires only the specification of a cross-sectional area, and does not deal with section thickness values.

**Comment by JohnDN90** [comment]
That's correct, the Nastran just defines the cross-sectional area directly in the PROD card, not dealing with thickness.

**Comment by JohnDN90** [comment]
If we don't modify the source, is there an efficient way to mathematically find a point that isn't colinear with a set of vectors?  The vectors being defined by v_i = node2_i - node1_i.

**Comment by manavbhatia** [comment]
Ok. I wonder how the stiffness matrix is transformed to the global system, since a transformation matrix is needed.  

Since the element matrix and vectors are purely along the local x-axis, it probably does not matter which way the local y- and z- vectors are oriented. Then, we can assume the vector to be anything that is not parallel to the element x-axis. 

I think that would do it.

**Comment by JohnDN90** [comment]
I agree, I had done testing with the arbitrary 1d section property card I coded up and set all section properties, except area, to zero for my test case.  I can assign any arbitrary y_vector and I still get the same result for a simple extension case as long as the y_vector is colinear with element's x-axis.

I'm looking through the source now to see if there is any way of automatically doing this, without the user having to manually ensure the y_vector isn't colinear with the element x-axis.

**Comment by manavbhatia** [comment]
> as the y_vector is colinear with element's x-axis.
I am assuming you mean "is not" collinear ?

> I'm looking through the source now to see if there is any way of automatically doing this, without the user having to manually ensure the y_vector isn't colinear with the element x-axis.

This should be done only for extension element that have no bending component. It would be easy to setup a case. The three basis vectors are (1, 0, 0), (0, 1, 0), (0, 0 1). We can take a cross-product of the element orientation vector with either of these and if the resulting vector has a non-zero length then that is the required vector. For example, given an element along (1, 0, 0), its cross product with (1, 0, 0) will be zero, but the other two vectors will be fine.

**Comment by JohnDN90** [comment]
Oops, yes, I meant **not** collinear.  

I have a few ideas to try, this discussion definitely helped so thank you.  I'm going to code a few things up and I'll let you know what I come up with.

**Comment by JohnDN90** [comment]
So far I've modified MAST::GeomElem::_init_local_elem_1d() and added a some logic to handle this.

If the y_vector hasn't been set (_local_y.size()==0), then it checks if the element is extension/torsion only.  If so, it then takes the element vector (node2 - node1), perturbs it arbitrarily and then assigns that as the _local_y vector.  Otherwise, it raises a libMesh error indicating y_vector was not defined.

The part I'm missing is the check where if the element is extension/torsion only, I currently just have that set to true for testing. I think the default should be what's currently implemented (torsion, bending, and extension), and the user should be able to set a flag to indicate the element should be extension/torsion only.  I'm currently looking through the source to find the best place to do this.

**Comment by manavbhatia** [comment]
There is a bending operator type enum defined in src/elasticity/bending_operator.h. One of its values is NO_BENDING, which means that bending is not to be used in the element formulation. 

The value for this is set in ElementPropertyCardBase and can be accessed through ElementPropertyCardBase::bending_model. 

I think your modification should work fine and that it would not cause other issues. 

Do you add a random perturbation to both nodes or only one? If you add perturbation to both, are you guaranteed a linearly independent perturbation?

**Comment by JohnDN90** [comment]
I didn't add a perturbation to either node directly.  I first calculate the vector connecting nodes 1 and 2, and then I perturb that vector,  so equivalently this is like perturbing only 1 node.

I actually just discovered the bending_operator stuff last week. But when I tried using it and set NO_BENDING in a 1D extension example problem, I get an error indicating "property not found for : kappa".  Looking at the stack trace, it looks like the TimoshenkoBendingOperator is calling the calculate_transverse_shear_residual.  It seems odd that NO_BENDING is resulting in the TimoshenkoBendingOperator being called, but I haven't look through the code to see how you implemented it yet.

**Comment by manavbhatia** [comment]
If the Timoshenko operator is being called with NO_BENDING set in the property card then it is a bug.

**Comment by JohnDN90** [comment]
I thought it might be, I'm looking through the source now to see if I can locate whats happening there.  Should we open move the discussion of NO_BENDING to a new issue?

**Comment by manavbhatia** [comment]
Sure.

**Comment by jdeaton** [comment]
@JohnDN90 should this issue be closed now? It seems like it should.

**Comment by JohnDN90** [comment]
Yes, I'll close it out. Looks like the mentions in commits got a little messy as we were merging stuff in from the other repo, but I confirmed 0c6d412 is in master and those changes are in there.
